name: build & packaging

on: [push, pull_request] 

jobs:
  build:
    strategy:
      matrix:
        java-version: [11]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK ${{matrix.java-version}}
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        cache: maven
        java-version: ${{matrix.java-version}}

    - name: Deploy to cnaf-releases
      uses: samuelmeuli/action-maven-publish@v1
      with:
        server_id: cnaf-releases
        nexus_username: ${{ secrets.NEXUS_USERNAME }}
        nexus_password: ${{ secrets.NEXUS_PASSWORD }}

    - name: Deploy to cnaf-snapshots
      uses: samuelmeuli/action-maven-publish@v1
      with:
        server_id: cnaf-snapshots
        nexus_username: ${{ secrets.NEXUS_USERNAME }}
        nexus_password: ${{ secrets.NEXUS_PASSWORD }}
